In [1]:
import pandas as pd
pd.set_option('display.max_columns', 40)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
%matplotlib inline

In [2]:
X = pd.read_csv('train_values.csv')
y = pd.read_csv('train_labels.csv')

X.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,n,f,q,t,d,1,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,o,r,n,x,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,t,r,n,f,x,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,t,r,n,f,x,s,d,0,1,0,0,0,0,1,1,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,t,r,n,f,x,s,d,1,0,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0

In [3]:
y.head()

   building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

In [4]:
X = X.merge(y, on = 'building_id')
y.drop(['building_id'], axis = 1, inplace = True)
y = np.asarray(y)
y = y.ravel()
y.shape

(260601,)

In [5]:
#X.head()

In [6]:
#X.dtypes

In [7]:
#X_category = X[[x for x in X.columns if X[x].dtype == 'object' or x == 'building_id']]
#X_category.head()

In [8]:
#X_int = X[['geo_level_1_id', 'geo_level_2_id', 'geo_level_3_id', 'count_floors_pre_eq', 'age', 'area_percentage', 'height_percentage', 'damage_grade']]
#X_int.head()

In [9]:
#fig, axs = plt.subplots(4, 2, figsize = (12, 12))
#fig.subplots_adjust(hspace = 0.5)
#sns.despine(left=True)

#cols = [x for x in X_int.columns]

#for i in range(0, 8):
    #sns.distplot(X[cols[i]], color = 'red', kde = True, ax = axs[i // 2, i % 2])
    
#plt.setp(axs)
#plt.tight_layout()

In [10]:
#fig, axs = plt.subplots(4, 2, figsize = (12, 12))
#fig.subplots_adjust(hspace = 0.5)
#sns.despine(left=True)

#cols = [x for x in X_int.columns]
#axs = axs.ravel()

#for i in range(0, 8):
    #axs[i].scatter(X[cols[7]], X[cols[i]])
    #axs[i].set_title('{} vs {}'.format(cols[7], cols[i]))
    
#plt.setp(axs)
#plt.tight_layout()

In [11]:
#X_int[['height_percentage', 'damage_grade']][X['height_percentage'] > 27].sum()

In [12]:
for col in ['geo_level_1_id', 'height_percentage']:
    sample = X[col].values.tolist()
    sample_normal = []
    m1 = min(sample)
    m2 = max(sample)
    for x in sample:
        z = (x - m1) / (m2 - m1)
        sample_normal.append(z)
    X[col] = np.array(sample_normal).T

In [13]:
for col in ['age', 'geo_level_2_id', 'geo_level_3_id']:
    sample = X[col].values.tolist()
    X[col] = np.array([np.log10(x) if x != 0 else x for x in sample]).T
    
X.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,damage_grade
0,802906,0.200000,2.687529,4.086289,2,1.477121,6,0.100000,t,r,n,f,q,t,d,1,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
1,28830,0.266667,2.954243,3.449015,2,1.000000,8,0.166667,o,r,n,x,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
2,94947,0.700000,2.559907,3.952938,2,1.000000,5,0.100000,t,r,n,f,x,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
3,590882,0.733333,2.621176,4.029140,2,1.000000,6,0.100000,t,r,n,f,x,s,d,0,1,0,0,0,0,1,1,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
4,201944,0.366667,2.117271,3.172603,3,1.477121,8,0.233333,t,r,n,f,x,s,d,1,0,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3